version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: amta-app
    ports:
      - "8081:8081"
    volumes:
      - ./logs:/var/log/amta
      - ./.env:/opt/amta/.env
      - ./.aws_credentials:/root/.aws/credentials
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - DEPLOYMENT_MODE=${DEPLOYMENT_MODE:-development}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - BEDROCK_MODEL_ID=${BEDROCK_MODEL_ID:-default-model}
    secrets:
      - aws_credentials
    restart: unless-stopped
    depends_on:
      - db
      - redis
    networks:
      - amta_network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G

  db:
    image: postgres:14
    container_name: amta-postgres
    environment:
      POSTGRES_DB: amta_greek
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - amta_network
    restart: unless-stopped

  redis:
    image: redis:6.2-alpine
    container_name: amta-redis
    volumes:
      - redis_data:/data
    networks:
      - amta_network
    restart: unless-stopped

networks:
  amta_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:

secrets:
  aws_credentials:
    file: ./.aws_credentials
