networks:
  amta-network:
    driver: bridge

services:
  postgres:
    image: postgres:14
    container_name: amta-postgres
    networks:
      amta-network:
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - DEPLOYMENT_MODE=${DEPLOYMENT_MODE:-production}
      - POSTGRES_DATA_DIR=${POSTGRES_DATA_DIR:-postgres_data}
      # Conservative performance tuning parameters
      - POSTGRES_MAX_CONNECTIONS=50  # Reduced from previous config
      - POSTGRES_SHARED_BUFFERS=512MB  # Moderate setting for t2.medium
      - POSTGRES_EFFECTIVE_CACHE_SIZE=1536MB  # 3/4 of available memory
      - LOG_LEVEL=debug
    volumes:
      - ${POSTGRES_DATA_DIR:-postgres_data}:/var/lib/postgresql/data
      - ~/amta/logs:/var/log/postgresql
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h ${POSTGRES_HOST} -p ${POSTGRES_PORT}"]
      interval: 120s
      timeout: 10s
      retries: 3
      start_period: 20s
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=512MB"
      - "-c"
      - "effective_cache_size=1536MB"
      - "-c"
      - "work_mem=32MB"  # Moderate setting
      - "-c"
      - "maintenance_work_mem=256MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=5GB"  # Reduced to conserve space
      - "-c"
      - "log_min_duration_statement=500ms"
      - "-c"
      - "idle_in_transaction_session_timeout=15s"
      - "-c"
      - "lock_timeout=2s"
      - "-c"
      - "statement_timeout=120s"  # 2 minutes
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=5000"
      - "-c"
      - "pg_stat_statements.track=all"
    ulimits:
      nproc: 65535
      nofile:
        soft: 26677
        hard: 46677
    shm_size: '512mb'  # Reduced from previous config

  backend:
    image: ghcr.io/atlogit/atlomy_chat-backend:${BACKEND_TAG}
    container_name: amta-backend
    networks:
      amta-network:
    ports:
      - "8081:8081"
    volumes:
      - ~/amta/logs:/amta/logs
      - ./.env:/amta/.env
      - ./alembic:/amta/alembic
      - ~/amta/lexical_values:/mnt/data/lexical_values  # Update JSON storage volume
    env_file:
      - .env
    environment:
      - POSTGRES_DATA_DIR=${POSTGRES_DATA_DIR:-postgres_data}:/var/lib/postgresql/data
      - PYTHONUNBUFFERED=1
      - DEPLOYMENT_MODE=${DEPLOYMENT_MODE:-production}
      - REDIS_URL=${REDIS_URL}
      - AWS_REGION=${AWS_REGION}
      - BEDROCK_MODEL_ID=${BEDROCK_MODEL_ID}
      - DATABASE_URL=${DATABASE_URL}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8081
      - LOGGING_CONFIG=/amta/logging_config.json
      - LOG_LEVEL=debug
      - DEBUG=true
      - JSON_STORAGE_BASE_DIR=/mnt/data/lexical_values  # Maintain JSON storage base directory
    restart: unless-stopped
    depends_on:
      - postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    image: ghcr.io/atlogit/atlomy_chat-frontend:${FRONTEND_TAG}
    #build:
    #  context: ./next-app
    #  dockerfile: Dockerfile
    container_name: amta-frontend
    networks:
      amta-network:
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${DEPLOYMENT_MODE:-production}
      - BACKEND_URL=http://localhost:8081
      - DEBUG=true
      - NEXT_PUBLIC_LOG_LEVEL=${DEPLOYMENT_MODE:-info}
    volumes:
      - ~/amta/logs:/app/logs
    restart: unless-stopped
    depends_on:
      - backend
    extra_hosts:
      - "localhost:172.17.0.1"
    command: >
      sh -c "npm run start > /app/logs/nextjs_debug.log 2>&1"

  redis:
    image: redis:6.2-alpine
    container_name: amta-redis
    command: >
      redis-server 
      --databases 16 
      --port ${REDIS_PORT} 
      --maxmemory 1gb
      --maxmemory-policy allkeys-lru
      --save 900 1 300 10 60 10000
    networks:
      amta-network:
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
      - DEPLOYMENT_MODE=${DEPLOYMENT_MODE:-production}
      - REDIS_LOG_LEVEL=${DEPLOYMENT_MODE:-notice}
    volumes:
      - redis_data:/data
      - ~/amta/logs:/var/log/redis
    restart: unless-stopped
    healthcheck:
      test: >
        /bin/sh -c "redis-cli -a $$REDIS_PASSWORD ping"
      interval: 120s
      timeout: 10s
      retries: 3
      start_period: 20s
    sysctls:
      net.core.somaxconn: 2048  # Moderate setting
    ulimits:
      nproc: 65535
      nofile:
        soft: 26677
        hard: 46677


volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
