version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile.backend
    container_name: amta-backend
    network_mode: "host"  # Use host network for direct localhost access
    ports:
      - "8081:8081"
    volumes:
      - ./logs:/atlomy_chat/logs
      - ./.env:/atlomy_chat/.env
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - DEPLOYMENT_MODE=production
      - REDIS_URL=${REDIS_URL}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - BEDROCK_MODEL_ID=${BEDROCK_MODEL_ID}
      - DATABASE_URL=${DATABASE_URL}
      - POSTGRES_HOST=localhost  # Explicitly set for host network mode
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8081
    restart: unless-stopped
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./next-app
      dockerfile: Dockerfile
    container_name: amta-frontend
    network_mode: "host"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - BACKEND_URL=http://localhost:8081
    restart: unless-stopped
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:6.2-alpine
    container_name: amta-redis
    network_mode: "host"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:
