"""Add unique constraint and handle duplicates

Revision ID: 55e2200734a2
Revises: add_title_fields
Create Date: 2024-10-28 00:55:35.255847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55e2200734a2'
down_revision: Union[str, None] = 'add_title_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_authors_reference_code', table_name='authors')
    op.create_index(op.f('ix_authors_reference_code'), 'authors', ['reference_code'], unique=True)
    op.add_column('text_divisions', sa.Column('line', sa.String(), nullable=True))
    op.drop_index('ix_text_divisions_author_id_field', table_name='text_divisions')
    op.drop_index('ix_text_divisions_is_title', table_name='text_divisions')
    op.drop_index('ix_text_divisions_title_number', table_name='text_divisions')
    op.drop_index('ix_text_divisions_work_number_field', table_name='text_divisions')
    op.drop_column('text_divisions', 'book_level_1')
    op.drop_column('text_divisions', 'book_level_3')
    op.drop_column('text_divisions', 'book_level_2')
    op.drop_column('text_divisions', 'book_level_4')
    op.create_index(op.f('ix_texts_reference_code'), 'texts', ['reference_code'], unique=False)
    op.drop_constraint('texts_author_id_fkey', 'texts', type_='foreignkey')
    op.create_foreign_key(None, 'texts', 'authors', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'texts', type_='foreignkey')
    op.create_foreign_key('texts_author_id_fkey', 'texts', 'authors', ['author_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_texts_reference_code'), table_name='texts')
    op.add_column('text_divisions', sa.Column('book_level_4', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('text_divisions', sa.Column('book_level_2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('text_divisions', sa.Column('book_level_3', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('text_divisions', sa.Column('book_level_1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_text_divisions_work_number_field', 'text_divisions', ['work_number_field'], unique=False)
    op.create_index('ix_text_divisions_title_number', 'text_divisions', ['title_number'], unique=False)
    op.create_index('ix_text_divisions_is_title', 'text_divisions', ['is_title'], unique=False)
    op.create_index('ix_text_divisions_author_id_field', 'text_divisions', ['author_id_field'], unique=False)
    op.drop_column('text_divisions', 'line')
    op.drop_index(op.f('ix_authors_reference_code'), table_name='authors')
    op.create_index('ix_authors_reference_code', 'authors', ['reference_code'], unique=False)
    # ### end Alembic commands ###
