"""add reference_code to author

Revision ID: 9bc4750c6e30
Revises: 71f5065b34ef
Create Date: 2024-10-26 01:22:09.631067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bc4750c6e30'
down_revision: Union[str, None] = '71f5065b34ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('reference_code', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_authors_reference_code'), 'authors', ['reference_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_authors_reference_code'), table_name='authors')
    op.drop_column('authors', 'reference_code')
    # ### end Alembic commands ###
