name: Database Connectivity Validation

on:
  workflow_dispatch:
    inputs:
      deployment_mode:
        description: 'Deployment mode (development/production)'
        required: false
        default: 'production'
  workflow_call:
    inputs:
      deployment_mode:
        description: 'Deployment mode (development/production)'
        type: string
        required: false
        default: 'production'

permissions:
  id-token: write
  contents: read

jobs:
  validate-database-connectivity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: us-east-1

      - name: Retrieve GitHub Actions Runner IP
        id: runner-ip
        run: |
          RUNNER_IP=$(curl -s https://api.ipify.org)
          echo "GitHub Actions Runner IP: $RUNNER_IP"
          echo "runner_ip=$RUNNER_IP" >> $GITHUB_OUTPUT

      - name: Add Temporary Security Group Rule
        env:
          SECURITY_GROUP_ID: ${{ secrets.EC2_SECURITY_GROUP_ID }}
          RUNNER_IP: ${{ steps.runner-ip.outputs.runner_ip }}
        run: |
          echo "Adding temporary access for IP: $RUNNER_IP"
          aws ec2 authorize-security-group-ingress \
            --group-id $SECURITY_GROUP_ID \
            --protocol tcp \
            --port 5432 \
            --cidr $RUNNER_IP/32

      - name: Retrieve Database Secrets
        id: get-database-secrets
        run: |
          secrets=$(aws secretsmanager get-secret-value --secret-id amta-production-secrets --query SecretString --output text)
          
          # Extract database connection details
          database_url=$(echo $secrets | jq -r '.DATABASE_URL')
          postgres_host=$(echo $secrets | jq -r '.POSTGRES_HOST')
          postgres_port=5432  # Explicitly set to 5432
          postgres_db=$(echo $secrets | jq -r '.POSTGRES_DB')
          postgres_user=$(echo $secrets | jq -r '.POSTGRES_USER')
          
          # Output parsed values with comprehensive logging
          echo "🔍 Database Connection Details:"
          echo "  Host: $postgres_host"
          echo "  Port: $postgres_port"
          echo "  Database: $postgres_db"
          echo "  User: $postgres_user"
          
          # Output values for workflow use
          echo "POSTGRES_HOST=$postgres_host" >> $GITHUB_OUTPUT
          echo "POSTGRES_PORT=$postgres_port" >> $GITHUB_OUTPUT
          echo "POSTGRES_DB=$postgres_db" >> $GITHUB_OUTPUT
          echo "POSTGRES_USER=$postgres_user" >> $GITHUB_OUTPUT

      - name: Validate Database Connectivity
        env:
          POSTGRES_HOST: ${{ steps.get-database-secrets.outputs.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ steps.get-database-secrets.outputs.POSTGRES_PORT }}
          POSTGRES_DB: ${{ steps.get-database-secrets.outputs.POSTGRES_DB }}
          POSTGRES_USER: ${{ steps.get-database-secrets.outputs.POSTGRES_USER }}
        run: |
          # Install PostgreSQL client
          sudo apt-get update
          sudo apt-get install -y postgresql-client

          # Retrieve database password securely
          POSTGRES_PASSWORD=$(aws secretsmanager get-secret-value \
            --secret-id amta-production-secrets \
            --query 'SecretString' \
            --output text | jq -r '.POSTGRES_PASSWORD')

          # Comprehensive connection attempt logging
          echo "🔬 Detailed Connection Attempt:"
          echo "  Hostname: $POSTGRES_HOST"
          echo "  Port: $POSTGRES_PORT"
          echo "  Database: $POSTGRES_DB"
          echo "  Username: $POSTGRES_USER"

          # Attempt database connection with timeout and detailed error handling
          export PGPASSWORD="$POSTGRES_PASSWORD"
          connection_output=$(timeout 10s psql \
            -h "$POSTGRES_HOST" \
            -p "$POSTGRES_PORT" \
            -U "$POSTGRES_USER" \
            -d "$POSTGRES_DB" \
            -t -c "SELECT 1" 2>&1)
          connection_status=$?
          
          # Detailed connection status reporting
          if [ $connection_status -eq 0 ]; then
            echo "✅ Database connection successful"
            echo "connection_status=success" >> $GITHUB_OUTPUT
          elif [ $connection_status -eq 124 ]; then
            echo "⏰ Database connection timed out"
            echo "❗ Connection Timeout Details:"
            echo "  Host: $POSTGRES_HOST"
            echo "  Port: $POSTGRES_PORT"
            echo "  Database: $POSTGRES_DB"
            echo "connection_status=timeout" >> $GITHUB_OUTPUT
            exit 1
          else
            echo "❌ Database connection failed"
            echo "❗ Detailed Connection Failure:"
            echo "  Host: $POSTGRES_HOST"
            echo "  Port: $POSTGRES_PORT"
            echo "  Database: $POSTGRES_DB"
            echo "  Connection Error: $connection_output"
            echo "connection_status=failed" >> $GITHUB_OUTPUT
            exit 1
          fi

      - name: Remove Temporary Security Group Rule
        if: always()
        env:
          SECURITY_GROUP_ID: ${{ secrets.EC2_SECURITY_GROUP_ID }}
          RUNNER_IP: ${{ steps.runner-ip.outputs.runner_ip }}
        run: |
          echo "Removing temporary access for IP: $RUNNER_IP"
          aws ec2 revoke-security-group-ingress \
            --group-id $SECURITY_GROUP_ID \
            --protocol tcp \
            --port 5432 \
            --cidr $RUNNER_IP/32

  notify-status:
    if: always()
    needs: [validate-database-connectivity]
    runs-on: ubuntu-latest
    steps:
      - name: Determine Workflow Status
        run: |
          if [[ "${{ needs.validate-database-connectivity.result }}" == "success" ]]; then
            echo "✅ Database Connectivity Validation Completed Successfully"
          else
            echo "❌ Database Connectivity Validation Failed"
            echo "🔍 Note: Failure expected during initial database setup"
            exit 1
          fi
