# GitHub Actions Feature Testing Workflow
# Validates new features and changes before merging
# Last updated: 2024-01-16
# Runs comprehensive tests on feature branches
name: Feature Branch Testing

on:
  push:
    branches-ignore:
      - main
      - develop
      - production
  pull_request:
    branches-ignore:
      - main
      - develop
      - production

jobs:
  feature-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: feature_test_amta
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:6
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install .
        pip install pytest pytest-asyncio
    
    - name: Run configuration validator
      run: python config_validator.py
      env:
        DATABASE_URL: postgresql+asyncpg://postgres:postgres@localhost/feature_test_amta
        REDIS_HOST: localhost
        AWS_BEDROCK_REGION: us-east-1
        AWS_BEDROCK_MODEL_ID: feature-test-model
    
    - name: Run feature-specific tests
      run: pytest tests/ -v
      env:
        DATABASE_URL: postgresql+asyncpg://postgres:postgres@localhost/feature_test_amta
        REDIS_HOST: localhost
        AWS_BEDROCK_REGION: us-east-1
        AWS_BEDROCK_MODEL_ID: feature-test-model

  feature-code-quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install code quality tools
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black mypy
    
    - name: Lint with flake8
      run: flake8 app/ tests/
    
    - name: Check formatting with black
      run: black --check app/ tests/
    
    - name: Type check with mypy
      run: mypy app/

  feature-security-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install security scanning tools
      run: |
        python -m pip install --upgrade pip
        pip install bandit safety
    
    - name: Run Bandit security scan
      run: bandit -r app/
    
    - name: Check dependencies for vulnerabilities
      run: safety check
